spring:
  application:
    name: practice
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
server:
  servlet:
    context-path: /practice