spring:
  application:
    name: producer
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
    path: /h2
logging:
  level:
    ROOT: INFO
server:
  servlet:
    context-path: /practice
topics:
  document:
    topic: document.topic