name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  SonarCloudScanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
          github-token: ${{secrets.GIT_TOKEN}}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=vcperes
            -Dsonar.projectKey=vcperes
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.java.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.jacoco.xmlReportPaths=coverage.xml