name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  SonarCloudScanner:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ 'producer', 'consumer' ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: ./${{ matrix.project }}
        run: mvn clean install
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=vcperes
            -Dsonar.projectKey=vcperes
            -Dsonar.java.binaries=.
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.java.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.jacoco.xmlReportPaths=coverage.xml
        working-directory: ./${{ matrix.project }}